name = "reprolegal"
main = "_worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "."
binding = "ASSETS"
# serves /countries from countries.html and /countries/ukraine from countries/ukraine.html
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "VIEWS"
id = "d2237735ebcb4ff687fe4bcb6e165cde"

[vars]
SITE_URL = "https://reprolegal.com"
